### ISSUE TITLE
Build time issue

### ISSUE THREAD

**Issue by gujjar1988** [mufassalhussain/flutter_paper_trail_plus#1]
It's not working with simulator.

"Lexical or Preprocessor Issue (Xcode): 'FlutterPaperTrailPlusPlugin.h' file not found
/Users/pankaj/.pub-cache/hosted/pub.dev/flutter_paper_trail_plus-0.0.2/ios/Classes/FlutterPaperTrailPlugin.m:0:8

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro."

**Comment by mufassalhussain** [comment]
The issue is resolved new update of package 0.0.3
